#!/bin/bash

PATHTOLIGHT=`grep "PATH" /usr/local/bin/backlightconfig | awk '{print $2}'`
numoflevels=`grep "LEVELS" /usr/local/bin/backlightconfig | awk '{print $2}'`
brightness=`cat $PATHTOLIGHT/brightness`
max=`cat $PATHTOLIGHT/max_brightness`

sname=`basename $0`

#Comment this out to use the global setting
numofulevels=100
#numofulevels=$numoflevels

incrsize=$(( $max/$numoflevels ))
incrusize=$(( $max/$numofulevels ))

cur_level=$(( $brightness/$incrsize ))
cur_ulevel=$(( $brightness/$incrusize ))

bri=$brightness

function adjustbrightness {
	echo $1 > $PATHTOLIGHT/brightness
	exit 0	
}

function help {
	echo "Correct usage:  $sname [OPTION]"
	echo "This script takes only one option, second will be discarded"
	echo "To increase backlight brightness:             $sname u"
	echo "To decrease backlight brightness:             $sname d"
	echo "To directly adjust backlight brightness:      $sname <NUM> (1-100 or 1-LEVELS according to your configuration)"
	echo "To turn backlight off:                        $sname off"
	echo "To display help                               $sname -h or $name --help"
}


if [ -z $1 ] ; then
	echo "Actual brightness:"
	echo "$brightness"
	echo ""
	echo "Brightness level (brightness controls) (Max=$numoflevels):"
	echo "$cur_level"
	echo ""
	echo "Brightness level (manual) (Max=$numofulevels):"
	echo "$cur_ulevel"
elif [ "$1" -eq "$1" ] 2>/dev/null ; then
        if [ $1 -gt $numofulevels ] ; then
                bri=$max
		adjustbrightness $bri
        elif [ $1 -lt 1 ] ; then
                bri=1
		adjustbrightness $bri
	elif [ $1 -le $numofulevels -o $1 -ge 1 ] ; then
		bri=$(( $1 * $incrusize ))
		adjustbrightness $bri
	else
		help
		exit 0
	fi
elif [ "$1" == "off" ] ; then
	bri=0
        adjustbrightness $bri
else
	case "$1" in
		-h|--help)
			help
			exit 0
			;;
		u|-u)
			if [ $brightness -ge $max ] ; then
				bri=$max
			elif [ $brightness == 0 ] ; then
				bri=1
			elif [ $brightness == 1 ] ; then
				bri=$incrsize
			else
				bri=$(( $brightness + $incrsize ))
			fi
			adjustbrightness $bri
			;;
		d|-d)
			if [ $brightness -le $incrsize ] ; then
				bri=1
			else
				bri=$(( $brightness - $incrsize ))
			fi
			adjustbrightness $bri
			;;
		*)
			help
			exit 0
			;;
	esac
fi
