#!/bin/bash
FONTSIZE=`echo "$1" | grep -E ^\-?[0-9]*\.?[0-9]+$ `

if [ -n "$FONTSIZE" ] ; then
  sed -i -r "s/(size = ).*/\1 $FONTSIZE/" .config/alacritty/alacritty.toml
  echo "New Font Size in alacritty.toml is: $FONTSIZE "
else
  FONTSIZE=`grep size ~/.config/alacritty/alacritty.toml | awk '{print $NF}'`
  echo "Current Font Size in alacritty.toml is: $FONTSIZE "
fi
