#!/bin/bash

PATHTOLIGHT=`grep "PATH" ~/.config/cftconf/backlight.d/backlight.conf | awk '{print $2}'`
NLEVELS=`grep "LEVELS" ~/.config/cftconf/backlight.d/backlight.conf | awk '{print $2}'`
STEP=`grep "STEP" ~/.config/cftconf/backlight.d/backlight.conf | awk '{print $2}'`

LASTKNOWN=~/.config/cftconf/backlight.d/.lastbacklight

CURRENT=`cat $LASTKNOWN 2>/dev/null`
if [ -z $CURRENT ] ; then
	CURRENT=`cat $PATHTOLIGHT/brightness`
	cat $PATHTOLIGHT/brightness > $LASTKNOWN
fi
MAX=`cat $PATHTOLIGHT/max_brightness`

SNAME=`basename $0`

INCR=$(( $STEP*$MAX/$NLEVELS ))
INCR_DEFAULT=$(( $MAX/100 ))

CURRENT_LEVEL=$(( $STEP*$CURRENT/$INCR ))

NEW=$CURRENT

function adjustbrightness {
  	#echo $1
	echo $1 > $PATHTOLIGHT/brightness
	cat $PATHTOLIGHT/brightness > $LASTKNOWN
	exit 0	
}

function help {
	echo "Correct usage:  $SNAME [OPTION]"
	echo "This script takes only one option, second will be discarded"
	echo "To increase backlight brightness:             $SNAME u"
	echo "To decrease backlight brightness:             $SNAME d"
	echo "To directly adjust backlight brightness:      $SNAME <NUM> (1-100)"
	echo "To turn backlight off:                        $SNAME off"
	echo "To display help                               $SNAME -h or $SNAME --help"
}


if [ -z $1 ] ; then
	cat $LASTKNOWN > $PATHTOLIGHT/brightness
	echo "Actual brightness:"
	echo "$CURRENT"
	echo ""
	echo "Brightness level (brightness controls) (Max=$NLEVELS):"
	echo "$CURRENT_LEVEL"
elif [ "$1" -eq "$1" ] 2>/dev/null ; then
        if [ $1 -ge 100 ] ; then
                NEW=$MAX
		adjustbrightness $NEW
        elif [ $1 -lt 1 ] ; then
                NEW=1
		adjustbrightness $NEW
	elif [ $1 -le 100 -o $1 -ge 1 ] ; then
		NEW=$(( $1 * $INCR_DEFAULT ))
		adjustbrightness $NEW
	else
		help
		exit 0
	fi
elif [ "$1" == "off" ] ; then
	NEW=0
        adjustbrightness $NEW
else
	case "$1" in
		-h|--help)
			help
			exit 0
			;;
		u|-u)
			if [ $CURRENT -ge $MAX ] ; then
				NEW=$MAX
			elif [ $CURRENT == 0 ] ; then
				NEW=1
			elif [ $CURRENT == 1 ] ; then
				NEW=$INCR
			else
				NEW=$(( $CURRENT + $INCR ))
			fi
			adjustbrightness $NEW
			;;
		d|-d)
			if [ $CURRENT -le $INCR ] ; then
				NEW=1
			else
				NEW=$(( $CURRENT - $INCR ))
			fi
			adjustbrightness $NEW
			;;
		*)
			help
			exit 0
			;;
	esac
fi

