#!/bin/bash


ARGS=$@

DEVICE="1:1:AT_Translated_Set_2_keyboard"

case $ARGS in
  e | E | en | enable | EN | ENABLE | Enable )
    swaymsg input $DEVICE events enabled
    echo "Laptop keyboard is enabled!"
    exit
    ;;
  d | D | dis | DIS | disable | DISABLE | Disable )
    swaymsg input $DEVICE events disabled
    echo "Laptop keyboard is disabled!"
    exit
    ;;
  * )
    echo "Wrong input, use e to enable and d to disable."
    exit
    ;;
esac
